<!DOCTYPE html>
<html>
<head>
	<style>
		/* Always set the map height explicitly to define the size of the div
		 * element that contains the map. */
		#map {
		  height: 50%;
		  width: 50%;
		}

		/* Optional: Makes the sample page fill the window. */
		html, body {
		  height: 100%;
		  margin: 0;
		  padding: 0;
		}
	</style>
</head>
<body>

<div id="map"></div>
<!-- Replace the value of the key parameter with your own API key. -->
<script async defer
src="https://maps.googleapis.com/maps">
</script>

<h1>hi</h1>
<!-- snip -->
<p>vehicle count: </p>
<div id="test"></div>
<div id="dom-target" style="display: none;">
	<?php
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt($ch, CURLOPT_URL, 'https://iotfam_esp32_singlechannel.data.thethingsnetwork.org/api/v2/query?last=7d');
		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
		curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');


		$headers = array();
		$headers[] = 'Accept: application/json';
		$headers[] = 'Authorization: key ttn-account-v2.3QymOg8dnB5OCLdVo_qpkNHHnALWXFXHI2R6BmorGJo';
		curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

		$result = curl_exec($ch);
		if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
		}
		
		curl_close ($ch);
		
		//$newstr =substr($result, 1 ,(strlen($result) - 3));
		//$data = json_encode($newstr);
		//echo $data;
		//echo $result;
		echo htmlspecialchars($result); /* You have to escape because the result
										will not be valid HTML otherwise. */
	?>        
</div>
<script>
	var div = document.getElementById("dom-target");
	var mydata = div.textContent;
	var myjson = JSON.parse(mydata);
	var index = myjson.length;
	document.getElementById("test").innerHTML = myjson[index].presence_1;
	var map;
	var streetColor;
	var presence_1 = myjson[index].presence_1;

	function initMap() {
			 map = new google.maps.Map(document.getElementById('map'), {
		zoom: 17,
		center: new google.maps.LatLng(32.778940, -117.072669),
		mapTypeId: 'roadmap' });
	  var trafficDensity = [
		{lat:32.778926,lng:-117.073239},
		{lat:32.779009,lng: -117.074885},
	  ];
	  
	  // Red is #FF0000, green is #32CD32, yellow is #FFBF00
	  var flightPath = new google.maps.Polyline({
		path: trafficDensity,
		geodesic: true,
		strokeColor: streetColor,
		strokeOpacity: 1.0,
		strokeWeight: 5,
	  });
	  // Create a <script> tag and set the USGS URL as the source.
	  var script = document.createElement('script');
	  script.src = 'http://3.16.209.133/speede/curl.php';
	  document.getElementsByTagName('head')[0].appendChild(script);
	  
	  flightPath.setMap(map);
	}

	  function displayColor() {
		if (presence_1 < 8 && presence_1 > 3) {
			streetColor = "#FF0000";
		} else if (presence_1 > 24) {
			streetColor = "#32CD32";
		} else {
			streetColor = "#FFBF00";
		}
	  }
	  
	  displayColor();
	  initMap();

</script>

</body>
</html>
